  version: "3"
  services:
    django:
      build: .
      container_name: django_app
      ports:
        - "8000:8000"
      volumes:
        - .:/app
        - static_volumes:/usr/src/app/static
        - media_volumes:/usr/src/app/media
      restart: always
      depends_on:
        - pgdb
      command: sh -c "python3 manage.py makemigrations && python3 manage.py migrate && gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    
    pgdb:
      image: postgres:alpine3.19
      environment:
        POSTGRES_DB: ${POSTGRES_NAME}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        
      container_name: pgdb
      volumes:
        - db_data:/var/lib/postgresql/data/
      ports:
        - "5438:5432"


    nginx:
      image: nginx
      ports:
        - 81:81
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        - static_volumes:/usr/src/app/static
        - media_volumes:/usr/src/app/media
      depends_on:
        - django

    # redis:
    #   image: redis
    #   ports:
    #     - "6379:6379"

    # celery:
    #   build: .
    #   command: celery -A config worker -l INFO

    #   depends_on:
    #     - django
    #     - redis


  volumes:
    static_volumes:
    media_volumes:
    db_data:
