# Generated by Django 4.2.3 on 2024-03-26 11:10

from django.db import migrations, models
import user_profiles.usermanager
import user_profiles.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(blank=True, max_length=30, null=True, verbose_name='Имя')),
                ('surname', models.CharField(blank=True, max_length=30, null=True, verbose_name='Фамилия')),
                ('password', models.CharField(max_length=128, validators=[user_profiles.validators.validate_password_strength], verbose_name='password')),
                ('email_or_phone', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('code', models.CharField(blank=True, max_length=6)),
                ('created_at', models.DateField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('number', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиент',
            },
            managers=[
                ('objects', user_profiles.usermanager.CustomUserManager()),
            ],
        ),
    ]
